"""initial schema

Revision ID: cb18e87bdf81
Revises: 
Create Date: 2025-10-04 05:23:24.785354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb18e87bdf81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_assignment_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('mercuriale_name', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_assignment_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('mercuriale_name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercuriale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('supplier_number', sa.String(), nullable=True),
    sa.Column('product_family', sa.String(), nullable=True),
    sa.Column('sub_family', sa.String(), nullable=True),
    sa.Column('sub_sub_family', sa.String(), nullable=True),
    sa.Column('sub_sub_sub_family', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name2', sa.String(), nullable=True),
    sa.Column('delivery_zone', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('required_range', sa.Boolean(), nullable=True),
    sa.Column('client_type', sa.String(), nullable=True),
    sa.Column('sub_client_type', sa.String(), nullable=True),
    sa.Column('mercuriale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mercuriale_id'], ['mercuriale.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_number')
    )
    op.create_table('mercuriale_products',
    sa.Column('mercuriale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('reduxcoef', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mercuriale_id'], ['mercuriale.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('mercuriale_id', 'product_id')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_order_line')
    op.drop_table('purchase_order')
    op.drop_table('mercuriale_products')
    op.drop_table('customer')
    op.drop_table('product')
    op.drop_table('mercuriale')
    op.drop_table('customer_assignment_rule')
    op.drop_table('customer_assignment_conditions')
    # ### end Alembic commands ###
